"""initial

Revision ID: 485218711ff5
Revises: 
Create Date: 2026-05-04 10:34:15.132840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '485218711ff5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('ix_audit_logs_occurred_at', 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('trajectory_score', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('direction_vector', sa.Float(), nullable=True),
    sa.Column('alignment_index', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_persons_canonical_id', 'persons', ['canonical_id'], unique=True)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_entity_id', sa.UUID(), nullable=False),
    sa.Column('from_type', sa.String(), nullable=False),
    sa.Column('to_entity_id', sa.UUID(), nullable=False),
    sa.Column('to_type', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_relationships_from', 'relationships', ['from_entity_id'], unique=False)
    op.create_index('ix_relationships_to', 'relationships', ['to_entity_id'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scrape_jobs_entity', 'scrape_jobs', ['entity_type', 'source'], unique=False)
    op.create_index('ix_scrape_jobs_status', 'scrape_jobs', ['status'], unique=False)
    op.create_table('startups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('maturity', sa.String(), nullable=True),
    sa.Column('problem_space', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_startups_canonical_id', 'startups', ['canonical_id'], unique=True)
    op.create_index('ix_startups_domain', 'startups', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_startups_domain', table_name='startups')
    op.drop_index('ix_startups_canonical_id', table_name='startups')
    op.drop_table('startups')
    op.drop_index('ix_scrape_jobs_status', table_name='scrape_jobs')
    op.drop_index('ix_scrape_jobs_entity', table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index('ix_relationships_to', table_name='relationships')
    op.drop_index('ix_relationships_from', table_name='relationships')
    op.drop_table('relationships')
    op.drop_index('ix_persons_canonical_id', table_name='persons')
    op.drop_table('persons')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_occurred_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
